// Realistic mock data for development without API keys.
// Swap in real keys via .env.local to get live data.

import type { Catalog, Offer, Store } from "@/lib/types";

const NOW = new Date();
const NEXT_WEEK = new Date(NOW.getTime() + 7 * 24 * 60 * 60 * 1000);
const fmt = (d: Date) => d.toISOString();

export const MOCK_OFFERS: Offer[] = [
  // Netto
  {
    id: "mock-netto-1",
    source: "salling",
    chain: "netto",
    name: "Kyllingefilet",
    description: "Dansk, 1 kg",
    originalPrice: 69.95,
    offerPrice: 49.95,
    discountPercent: 29,
    currency: "DKK",
    unit: "kg",
    imageUrl: "https://placehold.co/200x200?text=Kylling",
    validFrom: fmt(NOW),
    validUntil: fmt(NEXT_WEEK),
  },
  {
    id: "mock-netto-2",
    source: "salling",
    chain: "netto",
    name: "Æbler Gala",
    description: "Pose 1,5 kg",
    originalPrice: 29.95,
    offerPrice: 19.95,
    discountPercent: 33,
    currency: "DKK",
    unit: "pose",
    imageUrl: "https://placehold.co/200x200?text=Æbler",
    validFrom: fmt(NOW),
    validUntil: fmt(NEXT_WEEK),
  },
  {
    id: "mock-netto-3",
    source: "salling",
    chain: "netto",
    name: "Lurpak Smør",
    description: "500 g",
    originalPrice: 39.95,
    offerPrice: 29.95,
    discountPercent: 25,
    currency: "DKK",
    unit: "stk",
    imageUrl: "https://placehold.co/200x200?text=Smør",
    validFrom: fmt(NOW),
    validUntil: fmt(NEXT_WEEK),
  },
  // Føtex
  {
    id: "mock-foetex-1",
    source: "salling",
    chain: "foetex",
    name: "Laks Filet",
    description: "Norsk, 400 g",
    originalPrice: 59.95,
    offerPrice: 39.95,
    discountPercent: 33,
    currency: "DKK",
    unit: "stk",
    imageUrl: "https://placehold.co/200x200?text=Laks",
    validFrom: fmt(NOW),
    validUntil: fmt(NEXT_WEEK),
  },
  {
    id: "mock-foetex-2",
    source: "salling",
    chain: "foetex",
    name: "Mælk Minimælk",
    description: "Arla 2 × 2 L",
    originalPrice: 27.0,
    offerPrice: 19.0,
    discountPercent: 30,
    currency: "DKK",
    unit: "stk",
    imageUrl: "https://placehold.co/200x200?text=Mælk",
    validFrom: fmt(NOW),
    validUntil: fmt(NEXT_WEEK),
  },
  // Bilka
  {
    id: "mock-bilka-1",
    source: "salling",
    chain: "bilka",
    name: "Hakket Oksekød",
    description: "8–12% fedt, 500 g",
    originalPrice: 34.95,
    offerPrice: 24.95,
    discountPercent: 29,
    currency: "DKK",
    unit: "stk",
    imageUrl: "https://placehold.co/200x200?text=Oksekød",
    validFrom: fmt(NOW),
    validUntil: fmt(NEXT_WEEK),
  },
  // REMA 1000
  {
    id: "mock-rema-1",
    source: "rema",
    chain: "rema1000",
    name: "Svinekotelet",
    description: "Dansk, ca. 500 g",
    originalPrice: 44.95,
    offerPrice: 29.95,
    discountPercent: 33,
    currency: "DKK",
    unit: "stk",
    imageUrl: "https://placehold.co/200x200?text=Svinekotelet",
    validFrom: fmt(NOW),
    validUntil: fmt(NEXT_WEEK),
  },
  {
    id: "mock-rema-2",
    source: "rema",
    chain: "rema1000",
    name: "Kaffe Gevalia",
    description: "500 g, mellemristet",
    originalPrice: 59.95,
    offerPrice: 39.95,
    discountPercent: 33,
    currency: "DKK",
    unit: "stk",
    imageUrl: "https://placehold.co/200x200?text=Kaffe",
    validFrom: fmt(NOW),
    validUntil: fmt(NEXT_WEEK),
  },
  {
    id: "mock-rema-3",
    source: "rema",
    chain: "rema1000",
    name: "Pasta Penne",
    description: "500 g",
    originalPrice: 12.95,
    offerPrice: 7.95,
    discountPercent: 39,
    currency: "DKK",
    unit: "stk",
    imageUrl: "https://placehold.co/200x200?text=Pasta",
    validFrom: fmt(NOW),
    validUntil: fmt(NEXT_WEEK),
  },
  // 365discount
  {
    id: "mock-coop-1",
    source: "coop",
    chain: "365discount",
    name: "Ost Danbo 45+",
    description: "400 g skiver",
    originalPrice: 29.95,
    offerPrice: 19.95,
    discountPercent: 33,
    currency: "DKK",
    unit: "stk",
    imageUrl: "https://placehold.co/200x200?text=Ost",
    validFrom: fmt(NOW),
    validUntil: fmt(NEXT_WEEK),
  },
  {
    id: "mock-coop-2",
    source: "coop",
    chain: "365discount",
    name: "Æg friland",
    description: "10 stk, str. M/L",
    originalPrice: 29.95,
    offerPrice: 22.95,
    discountPercent: 23,
    currency: "DKK",
    unit: "bakke",
    imageUrl: "https://placehold.co/200x200?text=Æg",
    validFrom: fmt(NOW),
    validUntil: fmt(NEXT_WEEK),
  },
  // SuperBrugsen
  {
    id: "mock-coop-3",
    source: "coop",
    chain: "superbrugsen",
    name: "Jordbær",
    description: "Dansk, 500 g",
    originalPrice: 39.95,
    offerPrice: 24.95,
    discountPercent: 38,
    currency: "DKK",
    unit: "bakke",
    imageUrl: "https://placehold.co/200x200?text=Jordbær",
    validFrom: fmt(NOW),
    validUntil: fmt(NEXT_WEEK),
  },
];

export const MOCK_CATALOGS: Catalog[] = [
  {
    id: "mock-catalog-netto",
    source: "tjek",
    chain: "netto",
    title: "Netto — Ugens tilbud",
    validFrom: fmt(NOW),
    validUntil: fmt(NEXT_WEEK),
    pageCount: 16,
    coverImageUrl: "https://placehold.co/300x400?text=Netto",
  },
  {
    id: "mock-catalog-foetex",
    source: "tjek",
    chain: "foetex",
    title: "Føtex — Ugens tilbud",
    validFrom: fmt(NOW),
    validUntil: fmt(NEXT_WEEK),
    pageCount: 24,
    coverImageUrl: "https://placehold.co/300x400?text=Føtex",
  },
  {
    id: "mock-catalog-rema",
    source: "rema",
    chain: "rema1000",
    title: "REMA 1000 — Ugens tilbud",
    validFrom: fmt(NOW),
    validUntil: fmt(NEXT_WEEK),
    pageCount: 12,
    coverImageUrl: "https://placehold.co/300x400?text=REMA+1000",
  },
  {
    id: "mock-catalog-365",
    source: "coop",
    chain: "365discount",
    title: "365discount — Ugens tilbud",
    validFrom: fmt(NOW),
    validUntil: fmt(NEXT_WEEK),
    pageCount: 12,
    coverImageUrl: "https://placehold.co/300x400?text=365discount",
  },
];

export const MOCK_STORES: Store[] = [
  {
    id: "mock-store-netto-1",
    source: "salling",
    chain: "netto",
    name: "Netto Nørrebro",
    address: "Nørrebrogade 45",
    city: "København N",
    zipCode: "2200",
    lat: 55.6894,
    lng: 12.5492,
  },
  {
    id: "mock-store-rema-1",
    source: "rema",
    chain: "rema1000",
    name: "REMA 1000 Frederiksberg",
    address: "Falkoner Allé 9",
    city: "Frederiksberg",
    zipCode: "2000",
    lat: 55.6797,
    lng: 12.5302,
  },
];
